# Generated by Django 5.2.5 on 2025-11-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_thumbnail_url'),
        ('users', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='users.profile')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.DeleteModel(
            name='TrackEnrollment',
        ),
    ]
